### ISSUE TITLE
Мой отчет о результатах комита

### ISSUE THREAD

**Issue by UMSF-K13-2-Golubev** [UMSF-K13-2-Golubev/UMSF-K13-2-Golubev#1]
[K13-2-Golubev.docx](https://github.com/UMSF-K13-2-Golubev/UMSF-K13-2-Golubev/files/294258/K13-2-Golubev.docx)

**Comment by UMSF-K13-2-Golubev** [comment]
[K13-2-Golubev.docx](https://github.com/UMSF-K13-2-Golubev/UMSF-K13-2-Golubev/files/294253/K13-2-Golubev.docx)

**Comment by Smoktii** [comment]
ok
